name: hackathon_pwd_map
description: A new Flutter project for PWD accessibility mapping.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.4
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/campus_map.jpg